paths:
  /user/profile/{user_id}:
    get:
      tags:
        - mypage
      summary: 회원정보 불러오기
      description: user_id를 통해 회원 정보를 조회합니다.
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: success!
                  data:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        example: 1
                      access_token:
                        type: string
                        example: "abcde"
                      user_name:
                        type: string
                        example: "Manager"
                      email:
                        type: string
                        example: "manager@naver.com"
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-07-25T06:43:48"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON005"
                  message:
                    type: string
                    example: "요청한 페이지를 찾을 수 없습니다. 관리자에게 문의 바랍니다."
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON000"
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."
  /user/consulting/status/{consulting_id}:
    get:
      tags:
        - User
      summary: 상담 status 조회
      parameters:
      - name: consulting_id
        in: path
        required: true
        schema:
          properties:
            consulting_id:
              type: bigint
              description: 컨설팅 id
              example: 1
      responses:
        '200':
          description: 고민 내용 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: 
                  "consulting_id": 23
                  "house_size": "5평 ~ 10평"
                  "room_num": "2개"
                  "mood": "깔끔한 화이트톤"
                  "concern": "침대를 어디에 배치해야할지 모르겠어요."
                  "status": "step1"
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/consulting/{user_id}:
    get:
      tags:
        - User
      summary: 유저의 컨설팅 목록 조회
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          properties:
            consulting_id:
              type: bigint
              description: 유저의 id
              example: 1
      responses:
        '200':
          description: 유저의 컨설팅 목록 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: 
                  "consulting_id": 1
                  "house_size": "5평 ~ 10평"
                  "room_num": "2개"
                  "mood": "깔끔한 화이트톤"
                  "concern": "침대를 어디에 배치해야할지 모르겠어요."
                  "status": "step1"
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  